name: Release Version

on:
  milestone:
    types: [closed]

jobs:
  tag-release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download splitsh-lite
        run: |
          wget https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
          tar -xvf lite_linux_amd64.tar.gz
          mv  ./splitsh-lite bin/splitsh-lite

      - name: Run release
        run: bin/release ${{ github.event.milestone.title }}
