name: Release Version

on:
  milestone:
    types: [closed]

jobs:
  tag-release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run release
        id: composercache
        run: bin/release ${{ milestone.title }}
